services:
  - type: web
    name: flask-product-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn myapp:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: flask-product-db
          property: connectionString
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: cv_kay     
        sync: false

databases:
  - name: flask-product-db
    plan: free
